### ISSUE TITLE
Future feature suggestion : Can you somehow get the device-id and site-id also?

### ISSUE THREAD

**Issue by RasmusOtharKirketerp** [AThomsen/home-assistant_xolta_battery_authentication-addon#16]
I was wondering if it would be possible to kindly ask for your assistance? I've been using your code to get the authorization field and it's been super helpful. However, I was wondering if it might be possible to also retrieve the device-id and site-id?

If that's possible, it would be fantastic! It would really help prevent people from having to figure out how to get these items from dev.tools and use Python XOLTA API. Currently, in my project, https://github.com/RasmusOtharKirketerp/xolta_public, I have to hardcode the device-id and site-id in a config file, which isn't ideal.

Thank you so much in advance!

**Comment by AThomsen** [comment]
Hi

Take a look here https://github.com/AThomsen/home-assistant_xolta_battery/blob/bc1a8bb5cc4b41f56d1f9e2e137915330777dace/custom_components/xolta_batt/xolta_api.py#L178

I'm pretty sure device id is somewhere in there as well 😊

**Comment by AThomsen** [comment]
@RasmusOtharKirketerp - can we close this?
